# Generated by Django 3.2.3 on 2021-09-30 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_auto_20210929_1611'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickerwatcher',
            old_name='watcher',
            new_name='user',
        ),
    ]
