# Generated by Django 3.2.3 on 2021-10-12 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_image_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='as_url',
            field=models.TextField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar_url',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.image'),
        ),
    ]
