# Generated by Django 3.2.3 on 2021-10-12 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_auto_20211012_1640'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='avatar_url',
            new_name='avatar',
        ),
    ]
